# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Lenovo/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-17432-DESKTOP-NP5NV58/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.cache/wt [current_project]
set_property parent.project_path D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/ALU.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Add_Sub_unit.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Adder_4bit.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Bitwise_AND.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Bitwise_NOT.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Bitwise_OR.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Bitwise_XOR.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Com_1bit.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Comp_4bit.vhd
  {D:/Vivado_designs/Lab 07/Lab 07.srcs/sources_1/new/D_FF.vhd}
  {D:/Vivado_designs/Lab 4/Lab 4.srcs/sources_1/new/Decoder_2_to_4.vhd}
  {D:/Vivado_designs/Lab 4/Lab 4.srcs/sources_1/new/Decoder_3_to_8.vhd}
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/imports/new/FA.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/imports/new/HA.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Instruction_decoder_v2.vhd
  {D:/Vivado_designs/Lab 08/Lab 08.srcs/sources_1/new/LUT_16_7.vhd}
  {D:/Vivado_designs/Lab 05/Lab 05.srcs/sources_1/new/Multiplier_2.vhd}
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Mux_2_4bit.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Mux_8_4bit.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Mux_8_4bit_new.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Program_counter_v2.vhd
  {D:/Vivado_designs/Lab 3/Lab 3.srcs/sources_1/new/RCA_4.vhd}
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/ROM_v2.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Register.vhd
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Registers_Bank.vhd
  {D:/Vivado_designs/Lab 07/Lab 07.srcs/sources_1/new/Slow_Clk.vhd}
  D:/Vivado_designs/nano_processor_V1/nano_processor_V1.srcs/sources_1/new/Tri_State_buffer_4bit.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/right_shift_by1.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/right_shift_by2.vhd
  D:/Vivado_designs/Nano_processor_V2/Nano_processor_V2.srcs/sources_1/new/Nano_processor_V2.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_designs/Nano_processor_V2/Basys3Labs_for_Nano_processor_v2.xdc
set_property used_in_implementation false [get_files D:/Vivado_designs/Nano_processor_V2/Basys3Labs_for_Nano_processor_v2.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nano_processor_V2 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_processor_V2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_processor_V2_utilization_synth.rpt -pb Nano_processor_V2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
